# pyproject.toml

[project]
name = "gpyreg"
version = "0.1.0"
description = "Lightweight package for Gaussian process regression."
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "matplotlib",
    "numpy",
    "pytest",
    "pytest-rerunfailures",
    "scipy",
]
requires-python = ">=3.9"

[tool.setuptools]
packages = ["gpyreg"]

[project.optional-dependencies]
dev = [
    "sphinx",
]

[tool.black]
line-length = 79

[tool.isort]
skip_glob = []
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
profile = "black"

[tool.pycln]
all = true
